services:
  db:
    image: postgres:17
    container_name: backend_hw1_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  rabbit-data:
