name: DEPLOY

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy all
    runs-on: [
      "self-hosted",
      "demo"
    ] 
    defaults:
      run:
        working-directory: 'БР1.2/Едигарева Дарья/labs/hw6'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compose up
        run: |
          sudo docker compose -f docker-compose.micro.yml stop
          sudo docker compose -f docker-compose.micro.yml up --build -d

      - name: Cleanup
        run: docker system prune -a -f
